management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8080
  shutdown: graceful

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/userservice
    username: userservice
    password: pw123
  jpa:
    properties:
      hibernate:
        generate_statistics: false
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: false
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: true
  mvc:
    log-request-details: true
  lifecycle:
    timeout-per-shutdown-phase: "10s"
